// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace SmartLibraryManagementSystemClassLibrary.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20251029142540_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("SmartLibraryManagementSystemClassLibrary.Model.Book", b =>
                {
                    b.Property<int>("BookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("BookId"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("BookName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.HasKey("BookId");

                    b.ToTable("Book");
                });

            modelBuilder.Entity("SmartLibraryManagementSystemClassLibrary.Model.Catalog", b =>
                {
                    b.Property<int>("CatalogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CatalogId"));

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<int>("Copies")
                        .HasColumnType("int");

                    b.HasKey("CatalogId");

                    b.HasIndex("BookId")
                        .IsUnique();

                    b.ToTable("Catalog");
                });

            modelBuilder.Entity("SmartLibraryManagementSystemClassLibrary.Model.Faculty", b =>
                {
                    b.Property<int>("FacultyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("FacultyId"));

                    b.Property<string>("Course")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("varchar(2)");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("FacultyName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("FacultyId");

                    b.ToTable("Faculty");
                });

            modelBuilder.Entity("SmartLibraryManagementSystemClassLibrary.Model.Fine", b =>
                {
                    b.Property<int>("FineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("FineId"));

                    b.Property<int>("AmtPayedSinceLastFine")
                        .HasColumnType("int");

                    b.Property<int>("FineAmount")
                        .HasColumnType("int");

                    b.Property<int>("ReservatonId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("FineId");

                    b.HasIndex("ReservatonId")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("Fine");
                });

            modelBuilder.Entity("SmartLibraryManagementSystemClassLibrary.Model.Loan", b =>
                {
                    b.Property<int>("LoanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("LoanId"));

                    b.Property<int>("AmtLoanedSinceLastLoaned")
                        .HasColumnType("int");

                    b.Property<int>("LoanAmount")
                        .HasColumnType("int");

                    b.Property<int>("ReservatonId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoanId");

                    b.HasIndex("ReservatonId")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("Loan");
                });

            modelBuilder.Entity("SmartLibraryManagementSystemClassLibrary.Model.Reservation", b =>
                {
                    b.Property<int>("ReservationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ReservationId"));

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<int>("CatalogId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReservationTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ReservationId");

                    b.HasIndex("BookId");

                    b.HasIndex("CatalogId");

                    b.HasIndex("UserId");

                    b.ToTable("Reservation");
                });

            modelBuilder.Entity("SmartLibraryManagementSystemClassLibrary.Model.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("StudentId"));

                    b.Property<string>("Course")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("varchar(2)");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("varchar(5)");

                    b.Property<int>("Grade")
                        .HasColumnType("int");

                    b.Property<string>("StudentName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("StudentId");

                    b.ToTable("Student");
                });

            modelBuilder.Entity("SmartLibraryManagementSystemClassLibrary.Model.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("UserId"));

                    b.Property<int>("FacultyId")
                        .HasColumnType("int");

                    b.Property<bool>("HasFine")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("HasLoan")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsFaculty")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("UserName")
                        .HasMaxLength(50)
                        .HasColumnType("int");

                    b.HasKey("UserId");

                    b.HasIndex("FacultyId")
                        .IsUnique();

                    b.HasIndex("StudentId")
                        .IsUnique();

                    b.ToTable("User");
                });

            modelBuilder.Entity("SmartLibraryManagementSystemClassLibrary.Model.Catalog", b =>
                {
                    b.HasOne("SmartLibraryManagementSystemClassLibrary.Model.Book", "Book")
                        .WithOne("Catalog")
                        .HasForeignKey("SmartLibraryManagementSystemClassLibrary.Model.Catalog", "BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");
                });

            modelBuilder.Entity("SmartLibraryManagementSystemClassLibrary.Model.Fine", b =>
                {
                    b.HasOne("SmartLibraryManagementSystemClassLibrary.Model.Reservation", "Reservaton")
                        .WithOne("Fine")
                        .HasForeignKey("SmartLibraryManagementSystemClassLibrary.Model.Fine", "ReservatonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartLibraryManagementSystemClassLibrary.Model.User", "User")
                        .WithMany("PrevFine")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reservaton");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartLibraryManagementSystemClassLibrary.Model.Loan", b =>
                {
                    b.HasOne("SmartLibraryManagementSystemClassLibrary.Model.Reservation", "Reservaton")
                        .WithOne("Loan")
                        .HasForeignKey("SmartLibraryManagementSystemClassLibrary.Model.Loan", "ReservatonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartLibraryManagementSystemClassLibrary.Model.User", "User")
                        .WithMany("PrevLoan")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reservaton");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartLibraryManagementSystemClassLibrary.Model.Reservation", b =>
                {
                    b.HasOne("SmartLibraryManagementSystemClassLibrary.Model.Book", "Book")
                        .WithMany("Reservation")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartLibraryManagementSystemClassLibrary.Model.Catalog", "Catalog")
                        .WithMany("Reservations")
                        .HasForeignKey("CatalogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartLibraryManagementSystemClassLibrary.Model.User", "User")
                        .WithMany("Reservations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Catalog");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartLibraryManagementSystemClassLibrary.Model.User", b =>
                {
                    b.HasOne("SmartLibraryManagementSystemClassLibrary.Model.Faculty", "Faculty")
                        .WithOne("User")
                        .HasForeignKey("SmartLibraryManagementSystemClassLibrary.Model.User", "FacultyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartLibraryManagementSystemClassLibrary.Model.Student", "Student")
                        .WithOne("User")
                        .HasForeignKey("SmartLibraryManagementSystemClassLibrary.Model.User", "StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Faculty");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("SmartLibraryManagementSystemClassLibrary.Model.Book", b =>
                {
                    b.Navigation("Catalog")
                        .IsRequired();

                    b.Navigation("Reservation");
                });

            modelBuilder.Entity("SmartLibraryManagementSystemClassLibrary.Model.Catalog", b =>
                {
                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("SmartLibraryManagementSystemClassLibrary.Model.Faculty", b =>
                {
                    b.Navigation("User")
                        .IsRequired();
                });

            modelBuilder.Entity("SmartLibraryManagementSystemClassLibrary.Model.Reservation", b =>
                {
                    b.Navigation("Fine")
                        .IsRequired();

                    b.Navigation("Loan")
                        .IsRequired();
                });

            modelBuilder.Entity("SmartLibraryManagementSystemClassLibrary.Model.Student", b =>
                {
                    b.Navigation("User")
                        .IsRequired();
                });

            modelBuilder.Entity("SmartLibraryManagementSystemClassLibrary.Model.User", b =>
                {
                    b.Navigation("PrevFine");

                    b.Navigation("PrevLoan");

                    b.Navigation("Reservations");
                });
#pragma warning restore 612, 618
        }
    }
}
